-- phpMyAdmin SQL Dump
-- version 4.9.2
-- https://www.phpmyadmin.net/
--
-- Hôte : 127.0.0.1:3306
-- Généré le :  sam. 13 juin 2020 à 15:18
-- Version du serveur :  8.0.18
-- Version de PHP :  7.4.6

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données :  `symbnb`
--

-- --------------------------------------------------------

--
-- Structure de la table `ad`
--

DROP TABLE IF EXISTS `ad`;
CREATE TABLE IF NOT EXISTS `ad` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `price` double NOT NULL,
  `introduction` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `content` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `cover_image` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `rooms` int(11) NOT NULL,
  `slug` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `author_id` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `IDX_77E0ED58F675F31B` (`author_id`)
) ENGINE=InnoDB AUTO_INCREMENT=824 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Déchargement des données de la table `ad`
--

INSERT INTO `ad` (`id`, `title`, `price`, `introduction`, `content`, `cover_image`, `rooms`, `slug`, `author_id`) VALUES
(792, 'Provident recusandae cum exercitationem voluptas est est.', 132, 'Dolore nostrum at et facilis alias unde dolorem iure. Quia dolore a omnis recusandae aliquid sint. Quam id quo iusto quos molestiae.', 'Ea consequatur est sunt. Possimus dolor animi dolore id. Animi quidem consequuntur voluptatem esse beatae sint quia iusto. Quo nihil sed amet molestiae commodi explicabo ullam similique. Quod nam tempora non incidunt quaerat maxime tempore. Maxime est facilis inventore dolorem. Et rerum voluptate et facilis quaerat eveniet. Totam optio quibusdam consequuntur voluptates voluptas natus qui et.', 'https://picsum.photos/1000/350?random=1', 5, 'provident-recusandae-cum-exercitationem-voluptas-est-est', 168),
(793, 'Fugiat dolores corporis maxime ducimus.', 101, 'Sapiente qui blanditiis rem dolorem ut amet quidem. Sed ut tenetur minima fugit. Autem modi omnis corrupti ullam laudantium unde.', 'Consequuntur ducimus modi eum vero atque. Et voluptate et distinctio nihil. Assumenda illum delectus eum. Est voluptate impedit autem. Ad dolores nam nobis dolores voluptas repudiandae. Natus temporibus ut perferendis eum reprehenderit molestiae. Ipsa molestias similique odit et accusamus placeat ipsam. Cupiditate rerum quibusdam quas dolores fuga facilis voluptas. Culpa non autem qui voluptatem vel et.', 'https://picsum.photos/1000/350?random=2', 3, 'fugiat-dolores-corporis-maxime-ducimus-quae-vero', 169),
(794, 'Rerum ut id consequatur aut.', 130, 'Eum eaque tenetur omnis aut voluptates. Dolores vero sint rem fugiat fugit accusamus.', 'Reiciendis ratione ut ea enim. Cum id aut provident praesentium animi quos voluptatem. Et non deserunt distinctio quia consequatur consequatur. Architecto repudiandae ullam eligendi et veritatis. A quia saepe velit aut enim ut voluptatibus dolore. Esse culpa dolor omnis quasi possimus. Veniam doloribus fuga ut. Nemo tenetur atque officiis id facilis labore. Est id consequatur nihil autem laboriosam voluptate suscipit. Architecto ut omnis quod facere aut molestias temporibus quis.', 'https://picsum.photos/1000/350?random=3', 1, 'rerum-ut-id-consequatur-aut', 175),
(795, 'Placeat eaque non vitae voluptatum molestias.', 42, 'Nesciunt reiciendis architecto id et rerum provident. Non aut sit quisquam ea culpa. Autem voluptas sit qui aut laboriosam.', 'Modi ipsa quos numquam asperiores nam. Beatae ab iure ut iusto sint quia quidem. Enim nemo facilis praesentium magnam. Itaque inventore nostrum et maxime cupiditate. Et qui pariatur harum alias sit minus. Et dolore ad et vel eius. Molestias officiis velit et et eos quo culpa. Dolore qui aliquid voluptas et. Sit suscipit illo rerum. Quis a quod omnis animi consequatur architecto aliquid. Omnis atque ut illum molestiae nobis. Aut et inventore et. Repellat qui error in ut exercitationem dolores minus. Quia quaerat sint est beatae.', 'https://picsum.photos/1000/350?random=4', 5, 'placeat-eaque-non-vitae-voluptatum-molestias', 170),
(796, 'Ratione blanditiis accusantium enim quia temporibus.', 71, 'Sint quis recusandae et voluptatem reiciendis in vero. Deserunt quisquam cum illum maiores.', 'Explicabo beatae rerum earum quam rerum. Aliquid id illum impedit qui harum. Deserunt corporis et ex ut nihil aut fugiat ut. Enim maiores accusamus non sed. Sit aut fugit voluptas atque ut. Commodi sunt sed officia laborum nemo ducimus aperiam quia. Voluptatem quibusdam sed sit porro eaque aliquid. Fugit natus porro impedit autem voluptatem. Et deserunt magni eum nam voluptate eveniet asperiores dolorem. Tempore vero sint est quisquam dicta ipsa iure est. Sit nemo recusandae voluptatum enim beatae. Ratione modi atque laudantium blanditiis et.', 'https://picsum.photos/1000/350?random=5', 5, 'ratione-blanditiis-accusantium-enim-quia-temporibus', 176),
(797, 'Aut nisi doloribus omnis pariatur corporis.', 99, 'Modi similique aut facilis dolorem laborum dolor maiores. Voluptas assumenda a voluptatem est aut vel.', 'Veritatis dolorem quis sint voluptas vero. Velit quaerat dolor harum dolore. Deleniti sapiente iure soluta sed voluptas. Et et esse ex totam vel velit earum dicta. Sint enim voluptatum asperiores pariatur unde voluptate. Deserunt deserunt non et suscipit sed iure animi. Veniam quis ut hic quo. Error illo repudiandae non dolorem rerum et nemo.', 'https://picsum.photos/1000/350?random=6', 5, 'aut-nisi-doloribus-omnis-pariatur-corporis', 170),
(798, 'Modi labore ipsa tempora sit.', 48, 'Maiores dolores sunt hic repudiandae ut quaerat aspernatur. Doloribus quos autem sapiente.', 'Omnis consequuntur debitis nisi natus doloribus aut esse. Magni autem ut asperiores commodi. Corrupti perspiciatis et maxime autem molestiae qui nulla vel. Odit consequatur odio perferendis quaerat. Architecto voluptatum veritatis sed sed qui rerum sit. Quod cumque blanditiis tenetur sint tempora. Veritatis aperiam nostrum sed similique. Esse alias veritatis voluptatem id dolor voluptatum maiores. Voluptatem in a facere ipsum excepturi. Perferendis in veritatis doloremque eos id iste id. Quia commodi molestiae earum voluptatibus soluta ducimus qui. Alias maiores dolorem magnam id nostrum repudiandae.', 'https://picsum.photos/1000/350?random=7', 4, 'modi-labore-ipsa-tempora-sit', 171),
(799, 'Architecto dolore nulla molestiae qui autem tempore ea.', 85, 'Sit id omnis hic aspernatur. Rerum blanditiis itaque beatae voluptatibus molestiae.', 'Amet doloremque autem alias dolore officia nemo non. Possimus quia quas quia non itaque. Expedita placeat delectus non alias in dolores enim. Aut quo sequi distinctio. Omnis sapiente repellat perspiciatis ut. Occaecati nemo ex incidunt quo qui aut. Sit tempora tempore culpa aspernatur quo.', 'https://picsum.photos/1000/350?random=8', 5, 'architecto-dolore-nulla-molestiae-qui-autem-tempore-ea', 177),
(800, 'Facilis voluptas exercitationem maiores et dolorem.', 80, 'Voluptate dolor dolorem ut vitae sequi quo. Voluptas nesciunt nihil voluptas. Sunt nobis assumenda repellendus minus iste voluptas aperiam.', 'Nam modi soluta sed aut tempore pariatur et. Molestiae blanditiis omnis eius maiores explicabo veritatis vel. Atque neque repellat nemo quod et in. Veritatis consectetur itaque ipsa distinctio minus voluptatem velit quo. Quia quidem voluptatum quam earum expedita. Omnis laboriosam occaecati dolorem laudantium et sint iusto molestiae. Officiis est magnam qui minima qui. Quos corporis fugit maxime nihil perspiciatis pariatur unde non. Omnis consectetur vero perspiciatis iste accusantium. Distinctio modi eos rerum beatae minima quae.', 'https://picsum.photos/1000/350?random=9', 3, 'facilis-voluptas-exercitationem-maiores-et-dolorem', 172),
(801, 'Magnam architecto suscipit inventore.', 83, 'Rerum iusto voluptatem explicabo a ipsum velit harum perferendis. Voluptates repellendus et libero vel voluptatem. Voluptas quia rerum repudiandae sit enim perferendis fuga.', 'Et omnis et soluta ut voluptatem. Voluptatem aspernatur sint commodi voluptas. Odit expedita aut blanditiis ipsum aut doloribus. Laboriosam aut fugit illum totam nobis. Ab libero similique quia unde iusto maiores illum. Deserunt ullam ipsa illo quas reprehenderit. Aliquam sed soluta est. Aperiam placeat voluptates corrupti quo corporis ipsum inventore libero. Quis eos et qui eum magni nesciunt et totam. Aut impedit minima et qui quis voluptatem. Omnis aperiam vero omnis accusamus. Dolor tempore accusantium necessitatibus nesciunt labore sed est vel.', 'https://picsum.photos/1000/350?random=10', 2, 'magnam-architecto-suscipit-inventore', 168),
(802, 'Architecto vitae id omnis dolore labore consectetur ipsam.', 134, 'Amet eum tempore ea velit dolorum. Ipsa necessitatibus consequuntur odio. Et facilis est eum sint aspernatur deleniti et.', 'Nostrum perspiciatis quaerat sit magni quam excepturi distinctio. Nemo maxime quos voluptas quaerat similique officia sint. Tempore et numquam consequatur molestiae autem accusantium quia. Qui fugiat vel enim occaecati libero. Sequi tempora dolores est ex. Vero dolores totam a et velit cum atque id. Nulla eos quo porro voluptas. Eum illo illum velit dolores nobis corporis optio. Aut temporibus et doloribus. Libero reiciendis excepturi veniam non consequatur aut. Quia aut quibusdam optio repudiandae aut. Et nihil quaerat accusamus dolor dignissimos ad placeat.', 'https://picsum.photos/1000/350?random=11', 4, 'architecto-vitae-id-omnis-dolore-labore-consectetur-ipsam', 175),
(803, 'Corporis sit sed deserunt qui.', 61, 'Voluptatibus qui voluptatem aut eius. Dicta qui aliquam consequuntur consequatur. Modi rem quibusdam qui odio quasi ratione.', 'Reprehenderit sed distinctio est itaque quia. Aliquid modi ut voluptas rem adipisci accusantium. Velit facere et dolorum et quam nulla ab quia. Minima provident fugit et velit non nulla enim. Tempore placeat vel laudantium laboriosam. Autem non voluptatum repellat ducimus aliquam ullam ab. Molestias quia animi voluptatum ea. Quia reiciendis voluptatum similique optio consequuntur. Nisi exercitationem hic dignissimos voluptatem eos. Est fuga et dolore. Veritatis enim enim et totam excepturi ab. Perferendis itaque itaque voluptatibus ducimus voluptatem harum. Praesentium aperiam perspiciatis eligendi aut labore.', 'https://picsum.photos/1000/350?random=12', 4, 'corporis-sit-sed-deserunt-qui', 171),
(804, 'Est est quod necessitatibus labore veritatis illo.', 117, 'Voluptatem delectus et hic tenetur incidunt pariatur veritatis. Voluptatum totam ea eum accusantium.', 'Quibusdam natus ut fugit mollitia et eum asperiores. Incidunt magnam reiciendis qui aut. Fuga nulla sint autem sit in numquam ducimus. Adipisci eos impedit officiis et ipsa. Magnam facilis laboriosam quia sequi dolores et exercitationem. Sed perspiciatis vero iure quidem itaque reprehenderit modi. Non sint aut asperiores consequatur harum veritatis reprehenderit consequuntur. Esse enim omnis a et.', 'https://picsum.photos/1000/350?random=13', 2, 'est-est-quod-necessitatibus-labore-veritatis-illo', 174),
(805, 'Qui commodi dolor eaque nisi non quo.', 68, 'Pariatur dolorum accusamus necessitatibus quo voluptate quo. In ipsam consectetur eligendi voluptas voluptas aspernatur consectetur.', 'Magnam ut assumenda corrupti corrupti voluptate perferendis ut. Quis commodi libero sint quia enim aut quia assumenda. Eligendi voluptatem sit voluptas quas est ut. A facilis commodi quibusdam ut qui non iure. Nihil blanditiis quis reiciendis quam. Ducimus ut nostrum vel id doloribus. Tempora sed temporibus voluptate pariatur. Enim libero omnis voluptas nostrum. Nobis omnis commodi consequatur expedita consequuntur. Aspernatur vel fugiat consequatur placeat neque omnis voluptatem facere.', 'https://picsum.photos/1000/350?random=14', 4, 'qui-commodi-dolor-eaque-nisi-non-quo', 174),
(806, 'Qui adipisci reiciendis non rem ut necessitatibus.', 125, 'Et quidem dolores possimus delectus et. Exercitationem animi accusantium aperiam vitae ullam eaque. At magni provident tempora expedita et.', 'Minus incidunt molestiae cumque numquam. Voluptas doloremque ad incidunt consectetur illum doloremque et possimus. Voluptatem nesciunt velit non quia. Illum rem nam occaecati et. Ea quae repellendus eos tempora. Laboriosam facilis perferendis qui at aliquam molestias. Sint rerum in facilis corrupti voluptatem. Illum voluptatum sed quod dolore et. Reiciendis voluptatibus ea sed fugit qui perspiciatis iusto et.', 'https://picsum.photos/1000/350?random=15', 3, 'qui-adipisci-reiciendis-non-rem-ut-necessitatibus', 175),
(807, 'Quidem est tenetur sit corrupti nihil ipsam.', 53, 'Necessitatibus nihil hic laboriosam. Autem qui fugit provident optio.', 'Totam expedita in debitis dicta labore dolores. Eum consequatur praesentium aut et ratione. Praesentium tempore maiores molestias natus sunt voluptatum nihil. Natus numquam delectus sunt fugiat. Dolores sed in et laborum alias. Molestiae ut ut enim. Eaque accusamus harum eligendi quod sint qui blanditiis libero. Veritatis quis vel enim explicabo. Accusantium quaerat et officiis voluptate doloremque nam. Et vero eligendi omnis voluptatem animi iure consequuntur.', 'https://picsum.photos/1000/350?random=16', 2, 'quidem-est-tenetur-sit-corrupti-nihil-ipsam', 177),
(808, 'Optio unde cum voluptatem quisquam laudantium alias occaecati.', 80, 'Possimus itaque dolore facilis temporibus. Optio fugit autem totam veritatis quasi est voluptatibus ab. Non nihil nemo delectus non culpa alias.', 'Eius odio cumque officia aut at. Dolorem nobis nam velit voluptatibus reiciendis perspiciatis accusantium. Officiis distinctio nulla ullam vel ullam cum. Non voluptas veniam eius quod optio. Aut perferendis voluptatem vitae repellat illum laboriosam. Beatae et suscipit distinctio est sed voluptates voluptatum. Qui veritatis ducimus quidem. Est sapiente velit magni pariatur maxime ut et.', 'https://picsum.photos/1000/350?random=17', 3, 'optio-unde-cum-voluptatem-quisquam-laudantium-alias-occaecati', 175),
(809, 'Nobis aperiam eaque omnis consequatur quasi aut minima.', 138, 'Est pariatur laudantium omnis in maiores. Vel ipsum ut neque consequatur. Ut provident est accusamus repellat dolores ut.', 'Expedita enim tempore quam rem praesentium qui fugit dolorem. Aut qui vel fuga ipsam quia qui voluptatum. Voluptatem et harum autem officiis corrupti. Aut molestias voluptas rerum accusantium suscipit omnis. Aperiam sed et quia non ipsa esse. Amet facere sunt qui. Accusamus quia cum itaque non officiis est vitae recusandae. Odit harum et maxime ea. Consequatur doloribus facere hic qui maxime. Aut omnis sunt eos sint eaque. Sunt culpa ducimus beatae nam qui sit repellendus. Enim unde cum deserunt nisi.', 'https://picsum.photos/1000/350?random=18', 5, 'nobis-aperiam-eaque-omnis-consequatur-quasi-aut-minima', 168),
(810, 'Eum suscipit id minus at cum voluptate sequi.', 148, 'Cupiditate consequatur doloremque ea officiis aut ad laboriosam. In eum illo velit tempora non.', 'Et dolor expedita non occaecati expedita vel. Est sit esse animi veritatis eum sit officia. Officia possimus praesentium explicabo modi. Velit necessitatibus quidem id reiciendis reiciendis qui voluptate qui. Est odit quis rerum esse odit nihil. Placeat qui omnis aut debitis consequatur. A a qui autem natus quasi. Sit ea et est corrupti et. Cupiditate nihil quis dolores. Quis cupiditate non consequuntur error et eum.', 'https://picsum.photos/1000/350?random=19', 2, 'eum-suscipit-id-minus-at-cum-voluptate-sequi', 176),
(811, 'Molestias est voluptatem quam vel itaque aut.', 123, 'Culpa hic quia mollitia cum ea rerum. Est occaecati accusamus qui explicabo iste sequi excepturi nulla. Quia aliquid iure quas ex maiores.', 'Hic consequatur cumque laudantium quasi ut necessitatibus exercitationem. Nostrum eveniet velit deleniti ad. Consequuntur quia consequuntur eius ipsam. Quo enim laudantium sed at. Placeat ea omnis minus minus. Consequatur eveniet labore eum quas sunt vero. Rerum aliquid velit nam nobis tempora. Excepturi id tenetur est omnis incidunt commodi nihil. Soluta sit molestiae doloribus molestiae aut dolores deserunt officia.', 'https://picsum.photos/1000/350?random=20', 3, 'molestias-est-voluptatem-quam-vel-itaque-aut', 168),
(812, 'Itaque qui eius rerum unde sit qui cumque.', 131, 'Veniam molestiae est commodi sed. Officia porro quae recusandae aspernatur tempora earum dolor. Eum id earum aliquid quos aliquam qui adipisci.', 'Quia aut consectetur nemo qui. Quam corrupti placeat omnis quos ut. Dicta voluptates eveniet et omnis quo. Ut suscipit tempore exercitationem iure molestiae et ab. Qui quidem perferendis nam velit quia nobis. Id repudiandae iure nihil est modi rerum. Suscipit fuga iste voluptatem nostrum rerum enim. Maiores voluptatem ut repellat debitis. Architecto eum accusamus voluptas architecto exercitationem dolores. Qui architecto nesciunt incidunt sint aut et est. Modi natus provident quidem qui. At non dignissimos magni animi. Dolor culpa quibusdam voluptate.', 'https://picsum.photos/1000/350?random=21', 3, 'itaque-qui-eius-rerum-unde-sit-qui-cumque', 175),
(813, 'Magni ut nam ipsam voluptatem ea illum.', 93, 'Perspiciatis sint explicabo hic rerum. Nisi quisquam adipisci laborum.', 'Sed minus sit quasi est est. Perferendis dolor et aut cupiditate rerum reiciendis. Sit ducimus sequi nihil sed reiciendis officiis. Dolores consequuntur vero similique quidem sint maiores et. Ut et aut enim fugit iure deleniti. Magni quidem enim voluptatem molestiae sapiente omnis voluptatem. Beatae officiis reiciendis corporis debitis nemo sed enim. Rerum voluptates molestias necessitatibus nemo aut eum. Fuga quia dicta aperiam adipisci ab perspiciatis. Doloribus dolorem maxime quia sed. Nobis illo et est dolorum. Odit laudantium consectetur et in ducimus consequatur magni. Odit quo non consequatur provident. In fugit nam fugit alias dolores esse.', 'https://picsum.photos/1000/350?random=22', 2, 'magni-ut-nam-ipsam-voluptatem-ea-illum', 177),
(814, 'Explicabo et quidem saepe aut.', 139, 'Est expedita praesentium quidem rerum fugiat dignissimos aut. Rerum asperiores ex optio amet. Facere eos blanditiis itaque adipisci ullam.', 'Eius omnis nulla ut distinctio et omnis quo. Accusantium amet laborum recusandae saepe natus hic. Sequi nesciunt odio ratione velit amet consequuntur consectetur. Dolor est aut dolorem soluta omnis ipsum cum. Et id iste similique voluptatem ut alias ut. Quo id non impedit. Eos quisquam excepturi quia provident consequuntur quia.', 'https://picsum.photos/1000/350?random=23', 2, 'explicabo-et-quidem-saepe-aut', 171),
(815, 'Rerum aut error velit aut ipsam iste.', 79, 'Facilis atque non aliquid facere mollitia optio. Exercitationem rerum beatae soluta tempore nihil velit inventore.', 'Est quia ad nulla dolor illum. Aut autem dolores dolores repellendus voluptatibus sit voluptas libero. Quos qui commodi et velit ipsam omnis. Exercitationem velit vitae deserunt repudiandae recusandae eligendi. Odio dolor perferendis debitis et. Ut minima tempora velit illo optio aspernatur nemo autem. Sunt deserunt ipsam iste non. Est nostrum repellat temporibus quia harum. Quam magnam vel nemo reiciendis accusantium maxime suscipit. Qui ut dolorum quis itaque quidem voluptatem placeat odit. Magnam minus labore voluptas beatae. Modi et est eligendi. Magni et non totam nesciunt.', 'https://picsum.photos/1000/350?random=24', 3, 'rerum-aut-error-velit-aut-ipsam-iste', 170),
(816, 'Numquam earum quia eos ex.', 141, 'Qui dolor sint ut laboriosam qui. Est ut velit et aut qui voluptatem aliquid.', 'Earum culpa laudantium doloremque et eveniet. Similique quos odit suscipit facere sint doloribus sint. Et consequatur iusto ea non. Ullam quod velit placeat non. Qui animi culpa temporibus alias tempora. Itaque nesciunt reiciendis autem dolores quis dignissimos facilis. Omnis non vel magnam.', 'https://picsum.photos/1000/350?random=25', 3, 'numquam-earum-quia-eos-ex', 177),
(817, 'Error et et adipisci itaque repellendus.', 111, 'Iusto fugit id sequi sapiente et dolore sit. Odio sequi velit magnam qui sint et natus sed. Hic quaerat assumenda impedit at voluptatibus eligendi vel et.', 'Voluptatem consectetur fugiat eos illum velit vero et repudiandae. Alias et esse fugit praesentium dolores. Distinctio sed nihil et dolor. Voluptate libero voluptatem commodi delectus. Iusto error autem sequi fugiat incidunt ratione totam. Quaerat soluta et et non qui sequi. Aut culpa sit consectetur ipsam deserunt. Autem aut quas dolorem quia architecto. Accusamus perferendis quaerat esse.', 'https://picsum.photos/1000/350?random=26', 5, 'error-et-et-adipisci-itaque-repellendus', 176),
(818, 'Earum voluptatem sed doloribus.', 42, 'Doloribus aspernatur rerum accusamus ad. Et et eveniet sint dignissimos quaerat ut pariatur.', 'Qui ipsa porro minima in velit ut. Assumenda nam tempore eius enim consequatur. Quia est exercitationem recusandae consequatur eos deleniti voluptas. Necessitatibus quos et autem iusto consequatur molestias. Amet eos aut ut ducimus. Explicabo atque sit harum tempore explicabo cumque. Aliquid eos maxime voluptatibus. Accusamus est ea nam earum facilis. Quae ea ipsum minus veritatis quos earum provident. Delectus culpa minima atque non iure et. Accusamus nulla dolorum eos rem velit aliquam dolorem. Aut temporibus quas iure non et a aliquam.', 'https://picsum.photos/1000/350?random=27', 3, 'earum-voluptatem-sed-doloribus', 175),
(820, 'Rerum repudiandae et iure.', 134, 'Nobis id omnis explicabo ipsam quidem perferendis eligendi atque. Illum recusandae voluptas est autem et autem. Ut est illum veritatis aut itaque non.', 'Culpa sapiente at voluptatem impedit voluptatem. Assumenda modi esse aliquam doloribus. Enim hic occaecati voluptatum. Commodi sunt culpa dolore excepturi et sed dolor. Omnis eos quaerat facere eligendi ipsam vel reiciendis nostrum. Deserunt illum et occaecati tempore dolor. Consequatur placeat fugiat qui in illum provident. Voluptatum vitae ad dignissimos nostrum dolores. Ipsum illum dolorem blanditiis. Atque omnis error voluptatem officiis.', 'https://picsum.photos/1000/350?random=29', 4, 'rerum-repudiandae-et-iure', 170),
(821, 'Tempora est harum corrupti reprehenderit.', 58, 'Rerum qui voluptatem nihil exercitationem. Autem ea asperiores aut omnis.', 'Dolorem totam veniam incidunt ut sunt. Sed officia vero deserunt accusantium corporis adipisci. Laboriosam commodi doloremque mollitia autem ullam culpa saepe. Distinctio ipsa velit rerum ipsam. Vel nulla id error ut laborum deleniti. Porro ut et voluptatibus. Quis similique reiciendis culpa odio qui est repellendus aut. Optio voluptas esse sunt quia odit placeat. Sunt placeat quia sit ut cum.', 'https://picsum.photos/1000/350?random=30', 1, 'tempora-est-harum-corrupti-reprehenderit', 172),
(823, 'Nouvelle annonce', 150, 'Une description courte de ma nouvelle annonce', 'Une description un peu plus longue de ma nouvelle annonce après modification des fichiers css !!!', 'https://picsum.photos/1000/350?random=156', 3, 'nouvelle-annonce', 167);

--
-- Contraintes pour les tables déchargées
--

--
-- Contraintes pour la table `ad`
--
ALTER TABLE `ad`
  ADD CONSTRAINT `FK_77E0ED58F675F31B` FOREIGN KEY (`author_id`) REFERENCES `user` (`id`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
